import Constants from 'expo-constants';
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    screen: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 10,
    },
    searchRow: {
        alignItems: 'center',
        width: '100%',
        marginVertical: 10,
        flexDirection: 'row-reverse',
        justifyContent: 'space-between',
    },
    searchBox: {
        borderColor: 'grey',
        borderWidth: 1.5,
        width: '90%',
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 1,
        borderRadius: 5,
        flexDirection: 'row',
    },
    searchInput: {
        width: '80%',
        fontSize: 12,
        color: 'grey',
        fontFamily: 'Regular',
        paddingHorizontal: 5,
        textAlign: 'right',
    },
    listContent: {
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
    },
    card: {
        borderWidth: 1,
        borderColor: "#DDDDDD",
        borderRadius: 10,
        backgroundColor: "#FFF",
        paddingHorizontal: 10,
        paddingVertical: 5,
        marginVertical: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.36,
        shadowRadius: 6.68,
        elevation: 11,
    },
    cardHeader: {
        flexDirection: "row-reverse",
        alignItems: "center",
        justifyContent: "space-between",
    },
    leftCol: {
        width: "50%",
        alignItems: 'center',
    },
    chaletName: {
        fontFamily: "Bold",
        textAlign: 'right',
    },
    videoButton: {
        backgroundColor: 'red',
        padding: 5,
        flexDirection: 'row',
        borderRadius: 10,
    },
    videoButtonText: {
        fontFamily: "Bold",
        textAlign: 'right',
        color: '#FFF',
    },
    rightCol: {
        width: "50%",
    },
    ageBadge: {
        flexDirection: "row-reverse",
        justifyContent: 'space-between',
        alignItems: "center",
        backgroundColor: '#3D0A48',
        padding: 5,
        borderRadius: 10,
        width: '100%',
    },
    ageBadgeText: {
        fontFamily: "Regular",
        color: "#FFF",
        fontSize: 12,
    },
    priceText: {
        fontFamily: "Regular",
        textAlign: 'center',
    },
    descriptionBadge: {
        marginTop: 5,
        fontFamily: "Regular",
        textAlign: 'center',
        backgroundColor: "#51672D",
        padding: 5,
        borderRadius: 10,
        color: '#FFF',
        fontSize: 10,
    },
    cardBody: {
        flexDirection: "row-reverse",
        marginVertical: 20,
    },
    imageCol: {
        width: "40%",
        alignItems: "center",
        justifyContent: "center",
    },
    mainImage: {
        width: "100%",
        height: 260,
        borderRadius: 10,
        justifyContent: "flex-end",
    },
    galleryButton: {
        backgroundColor: "#1D4746",
        padding: 5,
        borderRadius: 5,
        flexDirection: "row-reverse",
        alignItems: "center",
    },
    galleryButtonText: {
        color: "#FFF",
        fontFamily: "Regular",
    },
    amenitiesCol: {
        width: "60%",
        paddingHorizontal: 5,
    },
    amenitiesGrid: {
        flexDirection: "row-reverse",
        flexWrap: "wrap",
        alignItems: "center",
        justifyContent: "space-between",
    },
    amenityItem: {
        width: "33%",
        alignItems: "center",
        justifyContent: "center",
    },
    amenityLabel: {
        fontFamily: "Bold",
        fontSize: 10,
        color: "#51672D",
        marginVertical: 1,
    },
    amenityValue: {
        fontFamily: "Regular",
        fontSize: 10,
        color: "#000",
        marginVertical: 1,
    },
    paymentBadge: {
        backgroundColor: "yellow",
        padding: 5,
        borderRadius: 5,
        marginTop: 10,
    },
    paymentText: {
        textAlign: "center",
        fontFamily: "Regular",
        fontSize: 12,
    },
    actionsRow: {
        flexDirection: "row-reverse",
        alignItems: "center",
        justifyContent: "space-between",
    },
    bookButton: {
        backgroundColor: "red",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 10,
        paddingVertical: 5,
        paddingHorizontal: 10,
        marginTop: 10,
        height: 40,
    },
    detailsButton: {
        backgroundColor: "#51672D",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 10,
        paddingVertical: 5,
        paddingHorizontal: 10,
        marginTop: 10,
        height: 40,
    },
    locationButton: {
        backgroundColor: "#00AA76",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 10,
        paddingVertical: 5,
        paddingHorizontal: 10,
        marginTop: 10,
        height: 40,
    },
    buttonText: {
        fontFamily: "Bold",
        color: "#FFF",
        fontSize: 10,
    },
    detailsModalContainer: {
        backgroundColor: "#FFF",
        width: "100%",
        borderRadius: 20,
        padding: 10,
        paddingTop: Constants.statusBarHeight + 10,
        height: 600,
    },
    detailsModalHeader: {
        borderBottomColor: "#DDDDDD",
        borderBottomWidth: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    detailsModalTitle: {
        fontFamily: "Bold",
        padding: 5,
    },
});
